config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :blog_posts

  # Defines the root path route ("/")
  root 'blog_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  # This ensures a blog title and message are present in the form
  has_one_attached :cover_image
  validates :caption, presence: true

  has_rich_text :content
  validates :title, presence: true
  validates :content, presence: true
  attribute :published_at, :datetime
  has_one_attached :photo

  extend FriendlyId
  friendly_id :title, use: :slugged

  def next
    BlogPost.where('id > ?', id).first
  end

  def prev
    BlogPost.where('id < ?', id).last
  end

  def should_generate_new_friendly_id?
    title_changed? || slug.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  def index
    @blog_posts = BlogPost.all
    @blog_posts = BlogPost.order(created_at: :desc)
  end

  def show
    @next_blog_post = @blog_post.next
    @prev_blog_post = @blog_post.prev
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      # Redirect to the show page for the newly created blog post
      redirect_to @blog_post
    else
      # Else, render the new template again
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :cover_image, :caption, :published_at)
  end

  def set_blog_post
    @blog_post = BlogPost.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def authenticate_user!
    redirect_to new_user_session_path, alert: 'Please sign in to continue.' unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div>
          <%= message %>
        </div>
        <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title, class: "w-1/2" %>
  </div>

  <div class="mt-4">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="mt-4">
    <%= form.label :cover_image %>
    <%= cl_image_tag blog_post.cover_image.key, class: "w-1/3" if blog_post.cover_image.present? %>
    <%# <%= form.file_field :cover_image %>
    <%= form.file_field :cover_image, as: :file, placeholder: "Insert photos", label: false %>
  </div>

  <div class="mt-4">
    <%= form.label :caption %>
    <%= form.text_field :caption %>
  </div>

  <div class="mt-4">
    <%= form.label :published_at %>
    <%= form.datetime_local_field :published_at %>
  </div>

  <div class="mt-4 w-1/4 bg-transparent hover:bg-blue-500 text-blue-700 text-center text-sm font-medium hover:text-white py-2 border border-blue-500 hover:border-transparent rounded">
    <%= form.button %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<section class="mx-auto md:w-3/4 px-10">
  <div class="edit-body mt-4">
    <h1 class="text-lime-800 no-underline font-semibold text-2xl font-thin uppercase font-serif mb-4">Edit blog post</h1>
    <div class="edit-form mb-40">
     <%= render partial: "form", locals: {blog_post: @blog_post} %>
      <div class="btn-del w-1/4 mt-4 bg-transparent hover:bg-red-500 text-sm text-red-700 text-center font-medium hover:text-white py-2 border border-red-500 hover:border-transparent rounded">
        <%= button_to "Delete Blog", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"} %>
      </div>
    </div>
  </div>
</section>

app/views/blog_posts/index.html.erb
<section class="mx-auto md:w-1/2 mb-20">
  <div class="blogs mb-6 px-10 pb-20 md:justify-center">
    <% @blog_posts.each do |blog_post| %>
      <div class="blog-card py-2 md:flex mb-4">
        <div class="cover-image pb-3 w-full md:w-32 lg:w-48 md:mr-6 relative">
          <%= link_to cl_image_tag(blog_post.cover_image.key, class: "rounded-sm w-full md:max-w-none object-cover object-center shadow-[rgba(0,_0,_0,_0.32)_0px_3px_8px]"),
              blog_post if blog_post.cover_image.present? %>
        </div>
        <div class="card-content w-3/4 md:ml-0">
          <h3>
            <%= link_to blog_post.title, blog_post, class: "text-lime-900 no-underline text-lg md:text-2xl font-thin uppercase font-sans hover:text-yellow-900 transition duration-300" %>
          </h3>
          <p class="font-light text-xs italic pt-1 pb-2">published: <%= time_ago_in_words(blog_post.created_at) %>
            ago
          </p>
          <div class="font-thin font-sans text-medium hidden md:block md:pb-2">
            <%= truncate(blog_post.content.to_plain_text, length: 100, omission: '...') %>
          </div>
          <%= link_to "read more >", blog_post_path(blog_post), class: "font-sans font-bold text-xs hover:text-yellow-900 transition duration-300" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/blog_posts/new.html.erb
<section class="mx-auto md:w-3/4 px-10">
  <new-blog-form>
    <h1 class= "text-lime-800 no-underline font-semibold text-2xl font-thin uppercase font-serif mb-4">
    Create new blog post
    </h1>
    <div class="blog-body pb-40">
      <%= render partial: "form", locals: {blog_post: @blog_post} %>
    </div>
  </new-blog-form>
</section>

app/views/blog_posts/show.html.erb
<section class="mx-auto md:w-2/4 px-10 mb-20">
  <div class="bach-btn pb-4">
    <%= link_to "< back home", root_path, class: "no-underline text-center text-sm font-sans font-thin hover:text-lime-900 transition duration-400" %>
  </div>

  <div class="post-content" data-controller="share reader" data-share-url-value="<%= blog_post_url(@blog_post) %>" data-share-title-value="<%= @blog_post.title %>">
    <div class="post-title">
      <h1 class="text-lime-800 no-underline font-extralight text-2xl font-thin capitalize font-sans md:text-3xl">
        <%= @blog_post.title %>
      </h1>
      <p class="font-thin text-xs pt-1 pb-2">
        published: <%= time_ago_in_words(@blog_post.created_at) %> ago
      </p>
      <p class="text-left pt-1 pb-4 font-thin text-xs">
        <%= content_tag(:span, "", data:{
        reader_target: "readingTime"
      }) %>
      </p>
      <div class="cover-image">
        <%= cl_image_tag @blog_post.cover_image.key, class: "h-320 w-600" if @blog_post.cover_image.present? %>
          <p class="font-light text-xs text-left pt-2 pb-4">
            <%= @blog_post.caption %>
          </p>
      </div>
    </div>
    <div class="post-body pb-8 font-thin">
      <p class="pb-2">
      ______
      </p>
      <p>
      <%= content_tag(:div, @blog_post.content, data: {
        reader_target: "content"
      }) %>
      <p>
        ______
      </p>
      <% if user_signed_in? %>
      <div class="py-6">
        <%= render 'shared/show_links' %>
      </div>
        <% else %>
        <div class="btn-share py-4 no-underline text-sm font-sans font-thin hover:text-lime-900 transition duration-400">
          <%= button_to "> share post", "", data: {action: "click->share#share"} %>
        </div>
        <%= render 'shared/blog_pagination' %>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IYRTIAMI by anthony marion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

 <body >
  <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <div>
        <%= yield %>
      </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_blog_pagination.html.erb
<section class="flex pt-8 pb-16">
  <btn-previous class="w-1/2 text-center border-r border-gray-200 no-underline sm:text-center text-sm py-4 font-sans font-thin font-semibold hover:text-lime-900 transition duration-400">
    <p>
      <%= link_to "< prev", @prev_blog_post if !@prev_blog_post.nil?%>
    </p>
  </btn-previous>
  <btn-next class="w-1/2 text-center no-underline sm:text-center text-sm py-4 font-sans font-thin hover:text-lime-900 transition duration-400">
    <p>
      <%= link_to "next >", @next_blog_post if !@next_blog_post.nil?%>
    </p>
  </btn-next>
</section>

app/views/shared/_footer.html.erb
<div class="w-full bg-white fixed bottom-0 py-2 border-t flex flex-col justify-center items-center">
  <div class="mx-auto text-center">
    <div class="footer-links flex justify-center items-center">
      <a href="mailto:anthonycmarion@gmail.com" class="no-underline sm:text-center text-sm font-sans font-thin font-semibold hover:text-lime-900 transition duration-400 px-3">contact</a>
      <a href="https://github.com/AntcMan" target="_blank" class="no-underline sm:text-center text-sm font-sans font-thin font-semibold hover:text-lime-900 transition duration-400 px-3">github</a>
    </div>
    <p class="sm:text-center text-xs pt-4 font-sans font-thin self-end"> &copy;<%= Time.current.year %> coded and designed by anthony marion</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class= "pt-8 px-8 md:px-0">
  <div class="title">
    <svg height="60" stroke="#bac736" stroke-width="2" class="text-line" width="100%">
      <text x="50%" dominant-baseline="middle" text-anchor="middle" y="50%">
        <%= link_to "IYRTIAMI.", root_path %>
      </text>
    </svg>
  </div>
  <p class="text-sm font-sans pt-1 font-thin text-center">
    if you're reading this <em class="text-highlight">i've almost made it</em>
  </p>
  <p class="text-sm font-sans pt-1 font-thin text-center pb-4" id="scroll-top">
    by anthony marion
  </p>
</div>
<div class="grid grid-cols-3 px-8 md:px-0 text-sm font-sans py-2 font-thin text-center">
  <% if user_signed_in? %>
    <div class="px-1">
      <%= link_to "Edit profile", edit_user_registration_path, class: "no-underline hover:underline font-medium" %>
    </div>
    <div class="px-1">
      <%= link_to "New blog", new_blog_post_path, method: :new, class: "no-underline hover:underline font-medium" %>
    </div>
    <div class="px-1">
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "no-underline hover:underline font-medium" %>
    </div>
    <% else %>
    <div class= "px-2 md:px-10 py-4">
      <% unless current_page?(root_path) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_show_links.html.erb
<div class="flex grid grid-cols-2">
  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_blog_post_path(@blog_post), class: "text-center no-underline hover:underline font-normal" %>
    <div class="flex justify-center items-center">
      <%= button_to 'Delete', @blog_post, method: :delete, data: {turbo_confirm: "Are you sure"}, class: "no-underline hover:underline text-yellow-900"  %>
    </div>
  <% end %>
</div>